### ISSUE TITLE
Query: Is this the best approach?

### ISSUE THREAD

**Issue by skills-up** [kjjdion/laracrud#1]
ReadMe says:

> The scaffolding only generates with a name attribute for the model. You will have to update your controller, model, migrations, views, and routes with any new attributes or functionality your app requires for the generated resource.
>
> Once you're ready, you can php artisan migrate to run the migrations for your new resource.

Since this leaves a lot of work to be done manually, specially when there are relationships involved (hasMany, belongsTo etc), it can lead to coding style differences and inconsistency.

Wouldn't it be better, if users start with creating a migration, and then the CRUD can be generated from artisan for the exact structure (including the relationships), without the need to manually edit all the files?

**Comment by kejodion** [comment]
This is a good idea but it introduces many complexities, especially in regards to UI generation. For example, we can obtain the column names and guess an input type (and hope we're right), but what if it is a select with options? What will those options be? What if the UI inputs are conditional? Also, we will need to implement the controller rules, etc. How are we to guess validation rules based on the migrations alone?

I've tried and created several of my own CRUD packages that had automated generators like you are talking about, and I always end up having to tweak things myself everywhere afterwards. Either because using the command line to generate attribute options is quite frankly, bad. Or, because the configuration has no separation of concerns and is simply confusing.

I have found that the best approach is to always do the work on your models, controllers, migrations, views, etc .manually, and simply use live templates in your IDE to make things fast, consistent, and easy. This is why this package only generates with a `name` attribute.

**Comment by skills-up** [comment]
Ah, actually I recently moved from Yii2 to Laravel. I was looking for
something similar to its gii based crud generator for Laravel, and this
project looked like the best match.

Your questions are valid for multiple UI options. I can only suggest what I
see gii doing, and what I've grown habitual of.

Gii generates CRUD in a GUI based manner, with options to customize and
choose between different alternatives (such as which UI widget to use).
However, let's say you make no choice, it will generate CRUD with default
options: radio buttons for Boolean, Select2 for enums, Text input for
varchar, and date/time/date time widgets for date fields.

Yet, you may not like to build such a complex system and I respect your
choice. Just saying having something of this sort would be good, as there
isn't any so far as I know.

**Comment by kejodion** [comment]
There are other packages with visual CRUD builders, and they all end up being too opinionated and a pain to customize IMO, especially when you start working on relationships etc. You can check out Voyager if you're interested.

I'd recommend you step as far away from what you're used to with Yii2 and throw yourself into the Laravel way of doing things. Again, just my opinion, but Laravel is many levels above Yii2.

**Comment by skills-up** [comment]
Thanks!

Regarding Voyager, I think I will try it after I've completely explored this project. Probably, both will be preferred tools over each other in different use cases.
